name: Deploy maboke243

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CUSTOM_DOMAIN: www.maboke243.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Copy index.html to 404.html
        run: |
          cp dist/index.html dist/404.html

      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gui-prod
          folder: dist
          cname: ${{ env.CUSTOM_DOMAIN }}
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
