name: Deploy maboke243

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CUSTOM_DOMAIN: www.maboke243.com

    steps:
    - uses: actions/checkout@v2
      with:
       node-version: '16'
    
    - name: Copy index.html to 404.html
      run: |
        cp dist/index.html dist/404.html
      
    - name: Build and deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: dist
        publish_branch: gui-prod
        cname: ${{ env.CUSTOM_DOMAIN }}
